website/blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('<slug:blogslug>',views.show,name='show'),
    path('',views.index,name='index'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='home'),
    path('blog/',include('blog.urls')),
    path('about/',views.about,name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

website/blog/models.py
from django.db import models
from django.utils.text import slugify

class kategori(models.Model):
    nama = models.CharField(max_length=40)
    keterangan = models.TextField(max_length=300)
    slug = models.SlugField(editable=False,blank=True,null=True)
    def save(self):
        self.slug = slugify(self.nama)
        super(kategori,self).save()

    def __str__(self):
        return self.nama
    

class artikel(models.Model):
    judul = models.CharField(max_length=50)
    isi = models.TextField(max_length=1000,null=True,blank=True)
    tanggal = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    kategori = models.ForeignKey(kategori,on_delete=models.SET_NULL,blank=True,null=True)
    slug = models.SlugField(editable=False,blank=True,null=True)
    gambar = models.ImageField(upload_to='media/',blank=True,null=True)


    def save(self):
        self.slug=slugify(self.judul)
        super(artikel,self).save()


    def __str__(self):
        return self.judul


class komen(models.Model):
    artikel = models.ForeignKey(artikel,on_delete=models.SET_NULL,blank=True,null=True)
    tanggal = models.DateTimeField(auto_now_add=True,blank=True,null=True) 
    isi = models.TextField(max_length=500,null=True,blank=True)
    email = models.EmailField(max_length=100,null=True,blank=True)

def __str__(self):
    return self.email

    
    

website/blog/forms.py
from django import forms

class komen_form(forms.Form):
    email = forms.EmailField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'masukan email'
            }
        )
    )
    isi = forms.CharField(
        max_length=500,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placheholder':'ini isi komentar'
            }
        )
    )

website/blog/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from . import models
from . import forms

def index(request):
    data_artikel = models.artikel.objects.all()
    context = {
        'halaman':'list artikel',
        'data':data_artikel,
    }
    return render(request, 'blog/index.html',context)

def show(request,blogslug):
    if request.method=='POST':
        models.komen.objects.create(
            artikel = models.artikel.objects.get(id=request.POST['kode']),
            email = request.POST['email'],
            isi = request.POST['isi'],
        )
        messages.success(request,'komentar Disimpan')
        return redirect('blog:show' ,blogslug)

    data_artikel = models.artikel.objects.get(slug=blogslug)
    data_komen = models.komen.objects.filter(artikel=models.artikel.objects.get(slug=blogslug)).order_by('-id')
    context = {
        'formnya':forms.komen_form(),
        'halaman':'detail artikel',
        'data':data_artikel,
        'komens':'data_komen',
    }
    return render(request, 'blog/show.html',context)

website/website/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    context = {
        'halaman':'home',
        'deskripsi':'ini halaman home',
        }
    return render(request, 'index.html', context)

def about(request):
    context = {
        'halaman':'about',
        'deskripsi':'ini halaman about',
    }
    return render(request, 'about.html', context)

website/blog/templates/blog/index.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container fluid">
    <br>
    <div class="text-center">
    <h1>{{halaman}}</h1>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for row in data %}
        <div class="col">
            <div class="card h-100">
                <img src="" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{row.judul}}</h5>
                    <p class="card-text">{{row.isi}}</p>
                    <p class="card-text"><small class="text-muted">update at {{row.tanggal}} - {{row.kategori}} </small></p>
                    <a href="{% url 'blog:show' row.slug %}" class="btn btn-block btn-primary">Read More</a>
                </div>
            </div> 
        </div> 
        {% endfor %}   
    </div>
</div>
{% endblock content %}

website/blog/templates/blog/show.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}
<div class="container fluid">
    <br>
    <div class="text-center">
        <h1>{{halaman}}</h1>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <img src="" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{data.judul}}</h5>
                    <p class="card-text">{{data.isi}}</p>
                    <p class="card-text"><small class="text-muted">update at {{data.tanggal}} -
                            {{data.kategori}}</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="card">
        <h5 class="card-header">Tinggal kan komentar</h5>
        <div class="card-body">
            {% for pesan in messages %}
            <div class="alert alert-{{pesan.tags}} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <strong>{{pesan}}</strong> Still on beta stage.
            </div>
            {% endfor %}
            <form method="POST" action="{% url 'blog:show' data.slug %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    {{formnya.email}}
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">komen</label>
                    {{formnya.isi}}
                    <input type="hidden" name="kode" value="{{data.id}}">
                </div>
                <button type="submit" class="btn btn-primary">Simpan</button>
                <button type="button" class="btn btn-danger" onclick="history.go(-1)">kembali</button>
            </form>
        </div>
        <br><br>
        <h3>Komentar</h3><br>
        <ul class="list-unstyled">
            {% for komen in komens %}
            <li class="media">
                <img class="mr-3" src="{% static 'img/user.png' %}" width="3%" alt="Generic placeholder image">
                <div class="media-body">
                    <h5 class="mt-0 mb-1">{{komen.email}}</h5>
                    {{komen.isi}} <br>
                    <span class="text-muted">{{komen.tanggal}}</span>
                </div>
            </li>
            <hr>
            {% endfor %}
        </ul>
    </div>
    {% endblock content %}

website/templates/about.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container fluid">
    <div class="jumbotron">
        <h1 class="display-4">Hello, ini halaman {{halaman}}</h1>
        <p class="lead">{{deskripsi}}</p>
    </div>
</div>
{% endblock content %}
   

website/templates/index.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="container fluid">
    <br>
    <div class="jumbotron">
        <h1 class="display-4">Hello, ini halaman {{halaman}}</h1>
        <p class="lead">{{deskripsi}}</p>
    </div>
</div>
{% endblock content %}

website/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
 
    <title>hello word</title>
</head>
<body>
    {% include 'layout/nav.html' %}
    
    {% block content %}
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
     
</body>

</html>

website/templates/layout/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Website</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'blog:index' %}" class="nav-link">Artikel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>